Update manual_grab.yml

diff --git a/.github/workflows/manual_grab.yml b/.github/workflows/manual_grab.yml
--- a/.github/workflows/manual_grab.yml
+++ b/.github/workflows/manual_grab.yml
@@ -8,26 +8,24 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: '20' # WAJIB 20 untuk memperbaiki "ReferenceError: File is not defined"
+          node-version: '20' # Agar tidak ada error "ReferenceError: File is not defined"
 
       - name: Install Dependencies
         run: npm install
 
       - name: Grab EPG
         run: |
-          npm run grab -- --site=indihometv.com --site=vidio.com --max-connections=1
+          npm run grab -- --site=indihometv.com --site=vidio.com
 
       - name: Commit and Push
         run: |
           git config --local user.email "github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git add guides/guide.xml
-          # Perintah || exit 0 agar tetap sukses meskipun tidak ada perubahan jadwal
+          # || exit 0 agar tetap sukses (hijau) meskipun tidak ada perubahan data
           git commit -m "Update EPG: $(date +'%Y-%m-%d %H:%M')" || exit 0
           git push origin master
